### ISSUE TITLE
Cart Functionality

### ISSUE THREAD

**Issue by SpazCode** [WASHTechGroup/ridgidware#6]
Cart Functionality is a staple in the current online commerce ecosystem. The cart tracks the users desired items and reserves that inventory for them. Due to this front end not having any e-commerce functionality the cart is just a protocol to reserve inventory.
## TO DO
- Make UX mock up 
- Create Database layout
- Build Controller
- Create transaction API design\
## Functionality Requirements ##`
- Reserve inventory
- Cart lifetime restrictions (ie only valid for x number of weeks)
- Cart transactions 
- Cashier access to carts
- User and Cashier cart creation

**Comment by hannahyeates** [comment]
Functionality Requirements:
- Reserve inventory, Cashier access to carts/Custom Orders - needs UI MockUp

**Comment by hannahyeates** [comment]
DO THIS FIRST:
- Add something to a cart from the inventory table
      - Use parts in carts table
      - In Parts in carts, you need to create a new entry that contains the cart ID and the part ID
      - 
- Build temporary cart building interface
  - Scaffolding does this
