### ISSUE TITLE
Inventory Control Back End

### ISSUE THREAD

**Issue by SpazCode** [WASHTechGroup/ridgidware#7]
Create a Back End to track the current 
## TO DO
- Create Database layout
- Create item catalog API design
- Build Controller
## Functionality Requirements ##
- Create a system to store the different items in the store
- Create a system that gets data for the items from APIs 
- A manual process to update inventory
- Ability to check inventory levels

**Comment by wsak** [comment]
Database is being built on "inventory-db" branch
